-- Generated by scripts/build_seed.py. Do not edit by hand.
-- Seed: infra-inventory-v0.1.0
-- Source SHA-256: 59c757f4a239955377a179d54e7427d51a6a96297d42d26d64e8a4cdd9bcc43b


DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM catalog.seed_releases
        WHERE seed_version = 'infra-inventory-v0.1.0'
          AND btrim(source_sha256) <> '59c757f4a239955377a179d54e7427d51a6a96297d42d26d64e8a4cdd9bcc43b'
    ) THEN
        RAISE EXCEPTION
            'seed version infra-inventory-v0.1.0 already exists with a different source checksum';
    END IF;
END;
$$;
INSERT INTO catalog.seed_releases (seed_version, source_uri, source_updated_at, source_sha256) VALUES
    ('infra-inventory-v0.1.0', 'https://github.com/seanwestfall/infra_timelapse/issues/1', '2026-08-02T05:46:46Z'::timestamptz, '59c757f4a239955377a179d54e7427d51a6a96297d42d26d64e8a4cdd9bcc43b')
ON CONFLICT (seed_version) DO NOTHING;
INSERT INTO catalog.countries (iso2, iso3, name) VALUES
    ('AE', 'ARE', 'United Arab Emirates'),
    ('AO', 'AGO', 'Angola'),
    ('AU', 'AUS', 'Australia'),
    ('BD', 'BGD', 'Bangladesh'),
    ('BR', 'BRA', 'Brazil'),
    ('CI', 'CIV', 'Côte d’Ivoire'),
    ('CM', 'CMR', 'Cameroon'),
    ('CN', 'CHN', 'China'),
    ('DE', 'DEU', 'Germany'),
    ('DJ', 'DJI', 'Djibouti'),
    ('DZ', 'DZA', 'Algeria'),
    ('EG', 'EGY', 'Egypt'),
    ('ER', 'ERI', 'Eritrea'),
    ('ES', 'ESP', 'Spain'),
    ('GH', 'GHA', 'Ghana'),
    ('GI', 'GIB', 'Gibraltar'),
    ('GN', 'GIN', 'Guinea'),
    ('GQ', 'GNQ', 'Equatorial Guinea'),
    ('GR', 'GRC', 'Greece'),
    ('HN', 'HND', 'Honduras'),
    ('ID', 'IDN', 'Indonesia'),
    ('IL', 'ISR', 'Israel'),
    ('IR', 'IRN', 'Iran'),
    ('KE', 'KEN', 'Kenya'),
    ('KH', 'KHM', 'Cambodia'),
    ('KW', 'KWT', 'Kuwait'),
    ('KZ', 'KAZ', 'Kazakhstan'),
    ('LK', 'LKA', 'Sri Lanka'),
    ('MA', 'MAR', 'Morocco'),
    ('MM', 'MMR', 'Myanmar'),
    ('MR', 'MRT', 'Mauritania'),
    ('MY', 'MYS', 'Malaysia'),
    ('MZ', 'MOZ', 'Mozambique'),
    ('NG', 'NGA', 'Nigeria'),
    ('NI', 'NIC', 'Nicaragua'),
    ('OM', 'OMN', 'Oman'),
    ('PA', 'PAN', 'Panama'),
    ('PE', 'PER', 'Peru'),
    ('PK', 'PAK', 'Pakistan'),
    ('PL', 'POL', 'Poland'),
    ('RU', 'RUS', 'Russia'),
    ('SG', 'SGP', 'Singapore'),
    ('SL', 'SLE', 'Sierra Leone'),
    ('TH', 'THA', 'Thailand'),
    ('TR', 'TUR', 'Türkiye'),
    ('TW', 'TWN', 'Taiwan'),
    ('TZ', 'TZA', 'Tanzania'),
    ('US', 'USA', 'United States'),
    ('YE', 'YEM', 'Yemen'),
    ('ZA', 'ZAF', 'South Africa')
ON CONFLICT (iso2) DO UPDATE SET iso3 = EXCLUDED.iso3, name = EXCLUDED.name;
INSERT INTO evidence.sources (source_id, url, title, publisher, source_kind, is_substantive, accessed_on, license_code) VALUES
    ('77f20175-69f4-51dd-8e1b-e96e5f826dc4', 'https://github.com/seanwestfall/infra_timelapse/issues/1', 'Infra Timelapse issue #1', 'GitHub', 'project_inventory', false, '2026-08-02'::date, NULL),
    ('ce266fd7-cde6-5b89-85e5-9b60f9d3a20c', 'https://www.data.gouv.fr/datasets/seaports-locations-data', 'Upply Seaports Locations Data', 'Upply', 'dataset', false, '2026-08-02'::date, 'CC BY'),
    ('88ebf2f1-6c98-544a-bdb4-6ed27e9e825e', 'https://www.openstreetmap.org/copyright', 'OpenStreetMap contributors via Nominatim and Overpass', 'OpenStreetMap contributors', 'coordinate', false, '2026-08-02'::date, 'ODbL'),
    ('86fd2ba8-8696-5c0a-97cb-ed3042fe383d', 'https://download.geonames.org/export/dump/', 'GeoNames geographical database', 'GeoNames', 'coordinate', false, '2026-08-02'::date, 'CC BY 4.0'),
    ('74c48f2c-e20e-54c5-929d-380fa50fd514', 'https://www.aiddata.org/data/chinese-financed-ports-overseas-and-related-terminals-dataset-2-0', 'Official port publications and corroborating open sources', 'AidData', 'dataset', true, '2026-08-02'::date, NULL),
    ('081f217c-8b5c-5831-a89e-3c4a3ef4ba36', 'https://eng.yidaiyilu.gov.cn/p/0KO9IB90.html', 'Official Belt and Road framework', 'Belt and Road Portal', 'official', true, '2026-08-02'::date, NULL)
ON CONFLICT (url) DO UPDATE SET
    title = EXCLUDED.title,
    publisher = EXCLUDED.publisher,
    source_kind = EXCLUDED.source_kind,
    accessed_on = EXCLUDED.accessed_on,
    license_code = EXCLUDED.license_code;
