-- Generated by scripts/build_seed.py. Do not edit by hand.
-- Seed: infra-inventory-v0.1.0
-- Source SHA-256: 2e5046ab5861be753753b791bdfe55f44ee2bff78aa67e98603f76b94a226f6e


DO $$
DECLARE
    actual_count integer;
BEGIN
    SELECT count(*) INTO actual_count
    FROM catalog.seed_release_entities AS release_entities
    JOIN catalog.entities AS entities
      ON entities.entity_id = release_entities.entity_id
    WHERE release_entities.seed_version = 'infra-inventory-v0.1.0'
      AND entities.entity_kind = 'node';
    IF actual_count <> 73 THEN
        RAISE EXCEPTION 'expected 73 seed nodes, found %', actual_count;
    END IF;

    SELECT count(*) INTO actual_count
    FROM catalog.seed_release_entities AS release_entities
    JOIN catalog.entities AS entities
      ON entities.entity_id = release_entities.entity_id
    WHERE release_entities.seed_version = 'infra-inventory-v0.1.0'
      AND entities.entity_kind = 'corridor';
    IF actual_count <> 19 THEN
        RAISE EXCEPTION 'expected 19 seed corridors, found %', actual_count;
    END IF;

    SELECT count(*) INTO actual_count
    FROM catalog.seed_release_entities AS release_entities
    JOIN catalog.entities AS entities
      ON entities.entity_id = release_entities.entity_id
    WHERE release_entities.seed_version = 'infra-inventory-v0.1.0'
      AND entities.entity_kind = 'project';
    IF actual_count <> 10 THEN
        RAISE EXCEPTION 'expected 10 seed projects, found %', actual_count;
    END IF;

    IF EXISTS (
        WITH expected(code, entity_id) AS (
            VALUES
                ('cor-aadj', '0f238b33-a444-50b8-9d44-26941c8b1f2f'::uuid),
                ('cor-bcim', '399ee36b-3db3-5687-9f7c-fc09e3c17dd3'::uuid),
                ('cor-bioceanic', 'ba814ab1-8b08-5b82-88a1-64b5930308bf'::uuid),
                ('cor-ccawa', '2bb7fa0e-0f50-5570-949c-57d300a98a25'::uuid),
                ('cor-cere', '3e77de65-18b7-56f3-96c4-892f152f0c03'::uuid),
                ('cor-cipc', 'a535df96-71cd-5247-90cb-0defe98b93de'::uuid),
                ('cor-cku', 'f2819cfd-de68-50da-9c06-ea95f56e9c1b'::uuid),
                ('cor-clr', '7d45022f-449c-5f64-921a-f0fc2cfd0479'::uuid),
                ('cor-cmec', '8fca158f-b81e-5d1e-b0c9-791a0002c676'::uuid),
                ('cor-cmrec', '055e3bab-4ab2-5548-9f0f-0bd9fd343d88'::uuid),
                ('cor-cpec', 'cfcab368-bede-56a1-a950-3aea39b3cac3'::uuid),
                ('cor-mombasa', 'cf769081-2ca3-553e-8b37-ea49fd09db18'::uuid),
                ('cor-msr', 'fe3edfb8-1300-50d5-a3c9-bac526ecb409'::uuid),
                ('cor-nelb', '4b800531-bd5d-5841-9192-0c9d2e402335'::uuid),
                ('cor-nilstc', 'ebbb449d-deda-5b74-9ddb-f67f148af214'::uuid),
                ('cor-pbb', '25eca93e-790c-53eb-bec7-edf950530414'::uuid),
                ('cor-polar-nsr', '81180a32-e961-50a7-8269-d71f169e348f'::uuid),
                ('cor-tazara', '9b507843-ac21-5a75-aa02-29c95df5541c'::uuid),
                ('cor-titr', '6f2fd468-a421-585b-bc1f-61df9e9b4949'::uuid),
                ('n-altynkol-rail-gateway', '446aa788-8b63-5079-b1e4-93c007e03f91'::uuid),
                ('n-autonomous-port-of-abidjan', 'fd351b44-061c-5de3-b262-0c7cd8b562b4'::uuid),
                ('n-autonomous-port-of-nouakchott', 'a65b2f09-3baf-5076-ac3d-af503ddac0a4'::uuid),
                ('n-bab-el-mandeb', '71e34440-1bbe-5de9-99cc-897525dc7cef'::uuid),
                ('n-bayport-terminal', '867328a3-c147-504d-aae3-2109996c8a2b'::uuid),
                ('n-beibu-gulf-port', '125c5c52-43fb-5239-83dc-0d724191bdd9'::uuid),
                ('n-bering-strait', 'ace7f899-a719-589f-98e3-1c20f520afe5'::uuid),
                ('n-bosporus', 'dfe7bfe6-e677-5292-ae92-8568d6084dc2'::uuid),
                ('n-cape-of-good-hope-route', '2cbbf296-a64d-5b50-a20d-ced94cbb6a9b'::uuid),
                ('n-chancay-port', '111e86e6-7415-5181-9250-cf99081e384f'::uuid),
                ('n-chattogram-port', 'd6e074b8-3462-5d6a-b6da-8be91f0a3c29'::uuid),
                ('n-cict-colombo', 'c6ab9fbf-be4d-599e-87ff-ee36097c7a89'::uuid),
                ('n-colombo-port', '936f8b47-f924-5356-a4be-5f36b9ae6f27'::uuid),
                ('n-csp-abu-dhabi-terminal', '6c9f48a9-3f3d-5466-9633-6cb0c65c668e'::uuid),
                ('n-damerjog-facilities', '19994ddf-45b7-528f-8e11-0bcaa8278027'::uuid),
                ('n-dar-es-salaam-port', '1e97ff4e-dc24-5db7-b472-d28eefe1e78b'::uuid),
                ('n-dardanelles', 'dd9fdf45-4b6b-5876-b02a-26e12131b5af'::uuid),
                ('n-doraleh-port', '69e7f007-3671-527f-91e2-22d57cc77ece'::uuid),
                ('n-duisburg-port', '87fcb392-9e3e-5057-8208-65f0afc0b71a'::uuid),
                ('n-duqm-port', '898d10b2-5b96-5590-a6c0-5253e7d88231'::uuid),
                ('n-el-hamdania-deepwater-port', 'e1e4ba05-65e2-5032-934e-5e304300c45c'::uuid),
                ('n-gwadar-port', '33b06830-1df4-5b67-a455-9017da9be106'::uuid),
                ('n-haifa-port', 'eef6944e-8d99-5088-982d-76bcd3d1ab85'::uuid),
                ('n-hambantota-port', 'bb69ed96-4bfc-543d-9834-8fe1f1e21e09'::uuid),
                ('n-horgos-gateway-cn', 'e6013c7c-1a6e-5c3a-a0fc-e313c26e89ab'::uuid),
                ('n-jurong-port-universal-terminal', '6d72e9bf-6a41-5bc5-93b7-1a8662b0de9b'::uuid),
                ('n-karachi-port', '3305fbc7-1743-5e12-ba25-c108e323be0c'::uuid),
                ('n-khalifa-port', '6bf0754b-b4ca-5439-96d2-25e5847eb211'::uuid),
                ('n-khorgos-eastern-gate-kz', 'c26df5c7-6a15-5900-8ed7-6ab979ba9327'::uuid),
                ('n-kisumu-port', '570b99cf-edb7-5132-b75c-59589fb1b605'::uuid),
                ('n-kribi-port', '7aa2b4a0-eb62-5df7-a880-5879001f1d0f'::uuid),
                ('n-kyaukphyu-port', 'c92ae902-af18-5d4c-a76f-9e22fd380d5e'::uuid),
                ('n-laem-chabang-port', '6876e596-2e7f-5d90-8860-4981a46b90ca'::uuid),
                ('n-lekki-port', 'e3125cfb-c1b4-511c-adae-ff58bcd295a9'::uuid),
                ('n-lianyungang-port', '37c99f6c-576a-5d7b-bf4c-c8e80bbf739e'::uuid),
                ('n-lombok-strait', '5ce9fee9-8eaf-537b-b7a3-567f96c6dbef'::uuid),
                ('n-malaszewicze-hub', '523a49c1-e251-5ce6-b775-94110b762a7e'::uuid),
                ('n-mombasa-port', '8ce13e2d-771a-52b0-8912-a7c8ca2b6939'::uuid),
                ('n-mongla-port', '8b369d4f-a4f2-5c8d-b6bd-37ebb90f0a82'::uuid),
                ('n-mubarak-al-kabeer-port', '6e9088bb-aaad-5390-a8d4-039b204efbef'::uuid),
                ('n-nacala-port', '743d9748-098e-544f-ba91-05b642f674ff'::uuid),
                ('n-nouadhibou-fishing-port', 'f4868030-4d45-516b-8d86-87905b1520a6'::uuid),
                ('n-panama-canal', 'c926d530-bedb-5324-a4ac-ce987109499f'::uuid),
                ('n-piraeus-port', '960c0144-db4d-5da6-a739-36c776be2cf5'::uuid),
                ('n-pla-base-djibouti', '8ccba2c4-3fc7-5168-8f81-95886535df75'::uuid),
                ('n-port-of-ashdod', '76196ccb-61ba-52f6-97e1-c361c10e84a7'::uuid),
                ('n-port-of-bata', '333b5711-d6cf-5b7a-9347-f2d064945709'::uuid),
                ('n-port-of-boffa-dapilon', '021353e8-a0c9-59e0-b371-cf1d7e91134a'::uuid),
                ('n-port-of-caio', 'e28511a1-4c29-5448-8425-306cac1d0e5a'::uuid),
                ('n-port-of-lobito', 'fb506fc8-5555-514a-a136-37a7c07b6b7e'::uuid),
                ('n-port-of-melbourne', '524449d2-152f-5959-863b-d11b2600454d'::uuid),
                ('n-port-of-newcastle', 'ce9cbbc3-1100-5d9b-be5c-0165dc9a58ba'::uuid),
                ('n-port-of-tema', 'db9ee6b5-0b5c-5e75-b65e-fd3d32865331'::uuid),
                ('n-port-of-valencia', 'b32a3b83-ab42-502d-8b86-a2bb51aa7bb7'::uuid),
                ('n-port-qasim', '47e4aa92-5b1d-5aab-9cd0-4f2583dcf819'::uuid),
                ('n-porto-sul', '0c0c34a9-6adf-52c8-96c6-629a09b4361c'::uuid),
                ('n-puerto-sandino', '234158d5-97f1-57d4-b919-c5b9e133673d'::uuid),
                ('n-qinzhou-port', 'bd9a3a3d-4615-533a-9a2a-a9454fb4a370'::uuid),
                ('n-queen-elizabeth-ii-quay', '4f7c7e45-9d95-579c-b53d-31ed67b001f5'::uuid),
                ('n-ream-joint-logistics-centre', 'ac8505c9-5836-58d8-a957-8b40f0d59bc9'::uuid),
                ('n-ream-naval-base', '7759d443-595d-5cd1-9ddb-44dd561f8cfd'::uuid),
                ('n-san-juan-de-marcona-port', 'cb851bbd-0b6a-5d2d-894a-90a9ae622c23'::uuid),
                ('n-san-lorenzo-port-honduras', '34ccaa2d-8ca8-55a4-8d87-37a149e610ff'::uuid),
                ('n-south-china-sea-approaches', '6bffa455-7948-531d-8f63-c23c9fe97677'::uuid),
                ('n-strait-of-gibraltar', '205652e1-a15e-5d53-a244-53a10ca00ddf'::uuid),
                ('n-strait-of-hormuz', '238c1d32-3bdf-5b49-8466-5d892ee53f4f'::uuid),
                ('n-strait-of-malacca', '16ac357f-c47a-5a66-9550-07557290f240'::uuid),
                ('n-suez-canal', 'd51c78e7-15c9-5ab9-a167-1cfc447de92f'::uuid),
                ('n-sunda-strait', 'a3602c6c-cf20-5aee-af9e-270a181bf6f0'::uuid),
                ('n-taiwan-strait', '8d6e86ed-f94a-5b4e-8b56-e10e3c924250'::uuid),
                ('n-tcp-paranagua', 'f31cf088-fd51-5b7e-a5d9-0f60a34c0171'::uuid),
                ('n-wiggins-island-coal-export-terminal', 'f43bb32b-4dca-5e01-b508-ef48010264b5'::uuid),
                ('n-xian-international-port', '98e7e47e-b6d8-5f6f-b182-a2d666647d0f'::uuid),
                ('prj-brazil-peru-feasibility-study', '7f0777db-1a3f-5c56-8c21-71585ba1d066'::uuid),
                ('prj-cku-railway', 'afc9c647-c747-5bd4-96f7-2700fbf5a37a'::uuid),
                ('prj-cmec-port-rail-components', '8f20696b-ae99-57f5-a755-7d9d2ed78c94'::uuid),
                ('prj-kyaukphyu-port-development', 'f3df9e79-88e4-5a5e-8e58-71829b2b033a'::uuid),
                ('prj-mombasa-inland-extensions', '44e68f4c-c99d-5a9e-bd13-79b7b19871c1'::uuid),
                ('prj-mongla-expansion', '1ff17100-4398-5843-bb16-9e3b4d45ce75'::uuid),
                ('prj-pan-asian-southern-links', '6e7b3a4d-ccf4-5e1c-a9ec-0a24764b8ed1'::uuid),
                ('prj-pbb-rail-buildout', 'f07e6203-4087-57bf-97b1-e9b70fa4c552'::uuid),
                ('prj-porto-sul-development', '21f61acd-d55f-53be-999b-f34ecac5bc7b'::uuid),
                ('prj-tazara-revitalization', 'f088eff3-e108-5212-b7fb-9fa031d5e16f'::uuid)
        )
        SELECT 1
        FROM expected
        LEFT JOIN catalog.entities USING (code)
        WHERE entities.entity_id IS DISTINCT FROM expected.entity_id
    ) THEN
        RAISE EXCEPTION 'one or more entity UUIDv5 values are not reproducible';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM catalog.entities AS entities
        JOIN catalog.seed_release_entities AS release_entities
          ON release_entities.entity_id = entities.entity_id
        WHERE release_entities.seed_version = 'infra-inventory-v0.1.0'
          AND entities.entity_kind = 'node'
          AND entities.canonical_name LIKE '%/%'
    ) THEN
        RAISE EXCEPTION 'canonical seed node names must not combine facilities with /';
    END IF;

    IF EXISTS (
        WITH expected(code, normalized_alias) AS (
            VALUES
                ('n-chattogram-port', 'chittagong-port'),
                ('n-el-hamdania-deepwater-port', 'hamdania-port'),
                ('n-malaszewicze-hub', 'malaszewicze-logistics-hub')
        )
        SELECT 1
        FROM expected
        JOIN catalog.entities USING (code)
        LEFT JOIN catalog.node_aliases
          ON node_aliases.node_id = entities.entity_id
         AND node_aliases.normalized_alias = expected.normalized_alias
        WHERE node_aliases.node_id IS NULL
    ) THEN
        RAISE EXCEPTION 'one or more required normalized aliases are missing';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM catalog.node_geometries
        WHERE ST_SRID(geom) <> 4326
           OR ST_NDims(geom) <> 2
           OR ST_IsEmpty(geom)
    ) THEN
        RAISE EXCEPTION 'seed node geometries must be nonempty 2D EPSG:4326 values';
    END IF;

    SELECT count(*) INTO actual_count
    FROM catalog.corridor_geometries AS corridor_geometries
    JOIN catalog.seed_release_entities AS release_entities
      ON release_entities.entity_id = corridor_geometries.corridor_id
    WHERE release_entities.seed_version = 'infra-inventory-v0.1.0'
      AND corridor_geometries.is_current;
    IF actual_count <> 19 THEN
        RAISE EXCEPTION 'expected 19 current corridor geometries, found %', actual_count;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM catalog.seed_release_entities AS release_entities
        JOIN catalog.entities AS entities
          ON entities.entity_id = release_entities.entity_id
        LEFT JOIN catalog.nodes ON catalog.nodes.entity_id = entities.entity_id
        LEFT JOIN catalog.corridors ON catalog.corridors.entity_id = entities.entity_id
        LEFT JOIN catalog.projects ON catalog.projects.entity_id = entities.entity_id
        WHERE release_entities.seed_version = 'infra-inventory-v0.1.0'
          AND (
              (entities.entity_kind = 'node' AND catalog.nodes.entity_id IS NULL)
              OR (entities.entity_kind = 'corridor' AND catalog.corridors.entity_id IS NULL)
              OR (entities.entity_kind = 'project' AND catalog.projects.entity_id IS NULL)
          )
    ) THEN
        RAISE EXCEPTION 'one or more seed entities are missing their subtype row';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM catalog.node_links AS links
        JOIN catalog.entities AS parent ON parent.entity_id = links.from_node_id
        JOIN catalog.entities AS child ON child.entity_id = links.to_node_id
        WHERE parent.code = 'n-ream-naval-base'
          AND child.code = 'n-ream-joint-logistics-centre'
          AND links.link_type = 'contains'
    ) THEN
        RAISE EXCEPTION 'Ream facilities were not normalized into linked nodes';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM catalog.nodes AS nodes
        JOIN catalog.corridor_nodes AS corridor_nodes
          ON corridor_nodes.node_id = nodes.entity_id
        WHERE nodes.monitoring_tier = 'overlay'
          AND (
              corridor_nodes.membership_type <> 'overlay'
              OR corridor_nodes.role <> 'overlay'
          )
    ) THEN
        RAISE EXCEPTION 'chokepoints and route overlays must use overlay membership only';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM catalog.nodes AS nodes
        JOIN evidence.entity_relationships AS relationships
          ON relationships.subject_entity_id = nodes.entity_id
        WHERE nodes.monitoring_tier = 'overlay'
    ) THEN
        RAISE EXCEPTION 'chokepoints and route overlays must not carry BRI/PRC assertions';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM catalog.nodes AS nodes
        JOIN evidence.entity_status_history AS status_history
          ON status_history.entity_id = nodes.entity_id
        WHERE nodes.monitoring_tier IN ('expanded', 'watchlist', 'overlay')
          AND status_history.effective_to IS NULL
          AND status_history.assertion_status <> 'superseded'
          AND status_history.lifecycle_status <> 'unknown'
    ) THEN
        RAISE EXCEPTION
            'expanded, watchlist, and overlay lifecycle claims must begin unknown';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM catalog.project_parties AS first_party
        JOIN catalog.project_parties AS second_party
          ON second_party.party_id > first_party.party_id
         AND second_party.project_id = first_party.project_id
         AND second_party.organization_id = first_party.organization_id
         AND second_party.party_role = first_party.party_role
         AND daterange(
                 COALESCE(second_party.effective_from, '-infinity'::date),
                 COALESCE(second_party.effective_to, 'infinity'::date),
                 '[]'
             ) && daterange(
                 COALESCE(first_party.effective_from, '-infinity'::date),
                 COALESCE(first_party.effective_to, 'infinity'::date),
                 '[]'
             )
    ) THEN
        RAISE EXCEPTION 'project party roles must not have overlapping effective periods';
    END IF;
END;
$$;

ANALYZE catalog.entities;
ANALYZE catalog.node_geometries;
ANALYZE catalog.corridor_geometries;

SELECT
    'infra-inventory-v0.1.0' AS seed_version,
    count(*) FILTER (WHERE entities.entity_kind = 'node') AS node_count,
    count(*) FILTER (WHERE entities.entity_kind = 'corridor') AS corridor_count,
    count(*) FILTER (WHERE entities.entity_kind = 'project') AS project_count
FROM catalog.seed_release_entities AS release_entities
JOIN catalog.entities AS entities
  ON entities.entity_id = release_entities.entity_id
WHERE release_entities.seed_version = 'infra-inventory-v0.1.0';
